import { useEffect,useState } from "react";
import { apiRequest } from "../api";
export default function Assignments({cfg}){
 const [students,setStudents]=useState([]),[teachers,setTeachers]=useState([]),[subjects,setSubjects]=useState([]),[teacherId,setTeacherId]=useState(""),[subjectId,setSubjectId]=useState(""),[selected,setSelected]=useState([]),[error,setError]=useState(""),[saved,setSaved]=useState("");
 useEffect(()=>{Promise.all([apiRequest("/students"),apiRequest("/teachers"),apiRequest("/subjects")]).then(([s,t,sub])=>{setStudents(s.students||[]);setTeachers(t.teachers||[]);setSubjects(sub.subjects||[])}).catch(e=>setError(e.message))},[]);
 function toggle(id){setSelected(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id])}
 async function save(){if(!teacherId||!subjectId||!selected.length){setError("Select a teacher, subject and at least one student.");return}try{await Promise.all(selected.map(id=>apiRequest(`/students/${id}/assign-teacher`,{method:"PUT",body:JSON.stringify({teacherId,subjectId})})));setSaved(`${selected.length} student(s) assigned successfully.`);setSelected([]);setTimeout(()=>setSaved(""),2500)}catch(e){setError(e.message)}}
 return <div className="page"><div className="page__header"><h2 className="page__title">Assignments</h2><p className="page__subtitle">Assign students to a teacher and subject</p></div>{error&&<div className="form-message form-message--error">{error}</div>}{saved&&<div className="form-message form-message--success">{saved}</div>}<div className="card assign-card"><div className="form-grid"><label className="form-group"><span className="form-label">Teacher</span><select className="form-select" value={teacherId} onChange={e=>setTeacherId(e.target.value)}><option value="">Select teacher</option>{teachers.map(t=><option key={t._id} value={t._id}>{t.fullName}</option>)}</select></label><label className="form-group"><span className="form-label">Subject</span><select className="form-select" value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Select subject</option>{subjects.map(s=><option key={s._id} value={s._id}>{s.name} ({s.code})</option>)}</select></label></div><div className="form-group"><label className="form-label">Select Students</label><div className="checkbox-list">{students.map(s=><label className="checkbox-item" key={s._id}><input type="checkbox" checked={selected.includes(s._id)} onChange={()=>toggle(s._id)} className="checkbox-input"/>{s.firstName} {s.lastName||""} · {s.studentId}</label>)}</div></div><button className="btn btn--primary" style={{backgroundColor:cfg.color}} onClick={save}>Save Assignment</button></div></div>
}
