import { useEffect,useState } from "react";
import Badge from "../components/Badge";
import { apiRequest } from "../api";
const STATUS_OPTIONS=["Present","Absent","Leave"];
export default function Attendance({cfg,role}){
 const [classes,setClasses]=useState([]),[subjects,setSubjects]=useState([]),[students,setStudents]=useState([]),[classId,setClassId]=useState(""),[subjectId,setSubjectId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[section,setSection]=useState(""),[statuses,setStatuses]=useState({}),[error,setError]=useState(""),[saved,setSaved]=useState("");
 async function loadBase(){try{const [c,s]=await Promise.all([apiRequest("/classes"),apiRequest("/subjects")]);setClasses(c.classes||[]);setSubjects(s.subjects||[])}catch(e){setError(e.message)}}
 useEffect(()=>{loadBase()},[]);
 useEffect(()=>{if(!classId)return;const cls=classes.find(c=>c._id===classId);setSection(cls?.sections?.[0]||"");apiRequest(`/students?class=${classId}`).then(d=>{const list=d.students||[];setStudents(list);const next={};list.forEach(s=>next[s._id]="Present");setStatuses(next)}).catch(e=>setError(e.message))},[classId]);
 async function loadAttendance(){if(!classId||!date)return;try{const q=new URLSearchParams({classId,date});if(subjectId)q.set("subjectId",subjectId);const d=await apiRequest(`/attendance?${q}`);setStatuses(prev=>{const next={...prev};(d.records||[]).forEach(r=>{if(r.student?._id)next[r.student._id]=r.status});return next})}catch(e){setError(e.message)}}
 useEffect(()=>{if(classId)loadAttendance()},[classId,subjectId,date]);
 async function save(){if(!classId||!subjectId||!section){setError("Select a class, subject and section first.");return}try{await apiRequest("/attendance",{method:"POST",body:JSON.stringify({classId,subjectId,section,date,records:students.map(s=>({studentId:s._id,status:statuses[s._id]||"Present"}))})});setSaved("Attendance saved successfully.");setTimeout(()=>setSaved(""),2500)}catch(e){setError(e.message)}}
 const selectedClass=classes.find(c=>c._id===classId);
 return <div className="page"><div className="page__header"><h2 className="page__title">Attendance</h2><p className="page__subtitle">Mark and save student attendance</p></div>{error&&<div className="form-message form-message--error">{error}</div>}{saved&&<div className="form-message form-message--success">{saved}</div>}<div className="card"><div className="form-grid"><label className="form-group"><span className="form-label">Class</span><select className="form-select" value={classId} onChange={e=>setClassId(e.target.value)}><option value="">Select class</option>{classes.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label className="form-group"><span className="form-label">Subject</span><select className="form-select" value={subjectId} onChange={e=>setSubjectId(e.target.value)}><option value="">Select subject</option>{subjects.map(s=><option key={s._id} value={s._id}>{s.name} ({s.code})</option>)}</select></label><label className="form-group"><span className="form-label">Section</span><select className="form-select" value={section} onChange={e=>setSection(e.target.value)}><option value="">Select section</option>{(selectedClass?.sections||[]).map(s=><option key={s} value={s}>{s}</option>)}</select></label><label className="form-group"><span className="form-label">Date</span><input className="form-input" type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div></div><div className="card">{students.length===0?<p className="empty-state">Select a class to load students.</p>:<div className="table-wrapper"><table className="data-table"><thead><tr><th>Roll</th><th>Student</th><th>Class</th><th>Status</th></tr></thead><tbody>{students.map(s=><tr key={s._id}><td>{s.rollNumber}</td><td>{s.firstName} {s.lastName||""}</td><td>{selectedClass?.name}-{section}</td><td><div className="att-btns">{STATUS_OPTIONS.map(opt=><button key={opt} onClick={()=>setStatuses({...statuses,[s._id]:opt})} className={`att-btn att-btn--${opt.toLowerCase()} ${statuses[s._id]===opt?"att-btn--selected":""}`}>{opt}</button>)}</div></td></tr>)}</tbody></table></div>}<button className="btn btn--primary att-save" style={{backgroundColor:cfg.color}} onClick={save} disabled={role!=="teacher"}>Save Attendance</button>{role!=="teacher"&&<p className="form-hint">Only teachers can save attendance.</p>}</div></div>
}
