import { useEffect,useState } from "react";
import { apiRequest } from "../api";
export default function Classes({role,cfg}){
 const [classes,setClasses]=useState([]),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[form,setForm]=useState({name:"",sections:""}),[error,setError]=useState("");
 const canEdit=role!=="teacher";
 async function load(){try{const d=await apiRequest("/classes");setClasses(d.classes||[])}catch(e){setError(e.message)}} useEffect(()=>{load()},[]);
 async function save(e){e.preventDefault();setError("");try{const body={name:form.name,sections:form.sections.split(",").map(s=>s.trim()).filter(Boolean)};if(editing)await apiRequest(`/classes/${editing}`,{method:"PUT",body:JSON.stringify(body)});else await apiRequest("/classes",{method:"POST",body:JSON.stringify(body)});setOpen(false);load()}catch(e){setError(e.message)}}
 async function remove(id){if(!confirm("Delete this class?"))return;try{await apiRequest(`/classes/${id}`,{method:"DELETE"});load()}catch(e){setError(e.message)}}
 return <div className="page"><div className="page__header"><div className="page__header-row"><div><h2 className="page__title">Classes & Sections</h2><p className="page__subtitle">Manage classes and sections</p></div>{canEdit&&<button className="btn btn--primary" style={{backgroundColor:cfg.color}} onClick={()=>{setEditing(null);setForm({name:"",sections:""});setOpen(true)}}>+ Add Class</button>}</div></div>{error&&<div className="form-message form-message--error">{error}</div>}<div className="class-cards">{classes.map(c=><div className="class-card" key={c._id}><p className="class-card__title" style={{color:cfg.color}}>{c.name}</p>{c.sections.map(s=><p className="class-card__section" key={s}>├── Section {s}</p>)}{canEdit&&<div className="card-actions"><button className="link-btn" style={{color:cfg.color}} onClick={()=>{setEditing(c._id);setForm({name:c.name,sections:(c.sections||[]).join(", ")});setOpen(true)}}>Edit</button><button className="link-btn danger-link" onClick={()=>remove(c._id)}>Delete</button></div>}</div>)}</div>{open&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><div className="modal-header"><h3>{editing?"Edit Class":"Add Class"}</h3><button type="button" className="modal-close" onClick={()=>setOpen(false)}>✕</button></div><label className="form-group"><span className="form-label">Class Name</span><input className="form-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Class 8" required/></label><label className="form-group"><span className="form-label">Sections</span><input className="form-input" value={form.sections} onChange={e=>setForm({...form,sections:e.target.value})} placeholder="A, B, C"/></label><div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn--primary" style={{backgroundColor:cfg.color}}>{editing?"Update Class":"Save Class"}</button></div></form></div>}</div>
}
