import { useEffect,useState } from "react";
import StatCard from "../components/StatCard";
import { apiRequest } from "../api";
export default function Dashboard({role,cfg,user}){
 const [data,setData]=useState(null),[error,setError]=useState("");
 useEffect(()=>{const endpoint=role==="teacher"?"/teachers/dashboard":"/dashboard";apiRequest(endpoint).then(d=>setData(d)).catch(e=>setError(e.message))},[role]);
 const d=data||{};const isTeacher=role==="teacher";
 return <div className="page"><div className="page__header"><h2 className="page__title">{isTeacher?`Welcome, ${d.welcome||user.fullName} 👋`:`${cfg.label} Dashboard`}</h2><p className="page__subtitle">{isTeacher?"Here's what's happening in your classes today.":"School overview for today"}</p></div>{error&&<div className="form-message form-message--error">{error}</div>}<div className="stats-grid">{isTeacher?<><StatCard label="My Subjects" value={d.mySubjectsCount??"—"} accent="green"/><StatCard label="My Classes" value={d.myClassesCount??"—"} accent="purple"/><StatCard label="My Students" value={d.myStudentsCount??"—"} accent="blue"/><StatCard label="Present Today" value={d.presentToday??"—"} accent="green"/><StatCard label="Absent Today" value={d.absentToday??"—"} accent="red"/></>:<><StatCard label="Total Students" value={d.totalStudents??"—"} accent={role==="principal"?"purple":"blue"}/><StatCard label="Total Teachers" value={d.totalTeachers??"—"} accent={role==="principal"?"blue":"purple"}/><StatCard label="Total Subjects" value={d.totalSubjects??"—"} accent="yellow"/><StatCard label="Present Today" value={d.presentToday??"—"} accent="green" sub={d.attendancePercentage?`${d.attendancePercentage}% attendance`:undefined}/><StatCard label="Absent Today" value={d.absentToday??"—"} accent="red"/><StatCard label={role==="principal"?"On Leave":"Pending Leaves"} value={role==="principal"?(d.onLeaveToday??"—"):(d.pendingLeaveRequests??"—")} accent="yellow"/></>}</div>{role==="principal"&&<div className="card"><h3 className="card__title">Today's Attendance Overview</h3><div className="att-bar"><div className="att-bar__segment att-bar__segment--green" style={{flex:d.presentToday||0}}/><div className="att-bar__segment att-bar__segment--red" style={{flex:d.absentToday||0}}/><div className="att-bar__segment att-bar__segment--yellow" style={{flex:d.onLeaveToday||0}}/></div><div className="att-bar__legend"><span className="att-bar__legend-item att-bar__legend-item--green">Present {d.presentToday||0}</span><span className="att-bar__legend-item att-bar__legend-item--red">Absent {d.absentToday||0}</span><span className="att-bar__legend-item att-bar__legend-item--yellow">Leave {d.onLeaveToday||0}</span></div></div>}</div>
}
