import { useEffect,useState } from "react";
import Badge from "../components/Badge";
import { apiRequest } from "../api";
const STATUS_TYPE={Pending:"warning",Approved:"success",Rejected:"danger"};
export default function Leaves({role,cfg}){
 const [requests,setRequests]=useState([]),[form,setForm]=useState({leaveType:"Personal",startDate:"",endDate:"",reason:""}),[error,setError]=useState(""),[saved,setSaved]=useState("");
 async function load(){try{const d=await apiRequest("/leaves");setRequests(d.leaves||[])}catch(e){setError(e.message)}}useEffect(()=>{load()},[]);
 async function submit(e){e.preventDefault();try{await apiRequest("/leaves",{method:"POST",body:JSON.stringify(form)});setForm({leaveType:"Personal",startDate:"",endDate:"",reason:""});setSaved("Leave request submitted.");load();setTimeout(()=>setSaved(""),2500)}catch(e){setError(e.message)}}
 async function review(id,status){try{await apiRequest(`/leaves/${id}/review`,{method:"PUT",body:JSON.stringify({status,rejectionReason:status==="Rejected"?"Rejected by management":undefined})});load()}catch(e){setError(e.message)}}
 const isTeacher=role==="teacher";
 return <div className="page"><div className="page__header"><h2 className="page__title">{isTeacher?"My Leave Requests":"Leave Requests"}</h2><p className="page__subtitle">Submit and review leave requests</p></div>{error&&<div className="form-message form-message--error">{error}</div>}{saved&&<div className="form-message form-message--success">{saved}</div>}{isTeacher&&<form className="card leave-form" onSubmit={submit}><h3 className="card__title">Submit Leave Request</h3><div className="form-grid"><label className="form-group"><span className="form-label">Leave Type</span><select className="form-select" value={form.leaveType} onChange={e=>setForm({...form,leaveType:e.target.value})}><option>Personal</option><option>Medical</option><option>Emergency</option></select></label><label className="form-group"><span className="form-label">Start Date</span><input className="form-input" type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})} required/></label><label className="form-group"><span className="form-label">End Date</span><input className="form-input" type="date" value={form.endDate} onChange={e=>setForm({...form,endDate:e.target.value})} required/></label></div><label className="form-group"><span className="form-label">Reason</span><textarea className="form-textarea" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} required/></label><button className="btn btn--primary" style={{backgroundColor:cfg.color}}>Submit Request</button></form>}<div className="card"><h3 className="card__title">{isTeacher?"My Requests":"All Requests"}</h3>{requests.length===0?<p className="empty-state">No leave requests found.</p>:requests.map(r=><div className="leave-row" key={r._id}><div><p className="leave-row__name">{r.teacher?.fullName||"Teacher"}</p><p className="leave-row__meta">{new Date(r.startDate).toLocaleDateString("en-GB")} → {new Date(r.endDate).toLocaleDateString("en-GB")} · {r.leaveType}</p><p className="leave-row__meta">{r.reason}</p></div><div className="leave-row__actions"><Badge text={r.status} type={STATUS_TYPE[r.status]}/>{!isTeacher&&r.status==="Pending"&&<><button className="btn btn--success" onClick={()=>review(r._id,"Approved")}>Approve</button><button className="btn btn--danger" onClick={()=>review(r._id,"Rejected")}>Reject</button></>}</div></div>)}</div></div>
}
