import { useEffect,useState } from "react";
import { Link } from "react-router-dom";
import { apiRequest } from "../api";
const roles=[{value:"SUPER_ADMIN",label:"Principal",description:"Full control over the school system."},{value:"MANAGER",label:"Manager",description:"Handles daily operations."},{value:"TEACHER",label:"Teacher",description:"Views assigned students and marks attendance."}];
const initial={role:"",fullName:"",email:"",phone:"",password:"",confirmPassword:"",employeeId:"",qualification:"",experience:""};
export default function Register(){const [availability,setAvailability]=useState({SUPER_ADMIN:true,MANAGER:true,TEACHER:true}),[form,setForm]=useState(initial),[error,setError]=useState(""),[success,setSuccess]=useState(""),[loading,setLoading]=useState(false);
 useEffect(()=>{apiRequest("/auth/role-availability").then(d=>setAvailability(d)).catch(()=>{})},[]);
 function update(k,v){setForm(p=>({...p,[k]:v}));setError("")}
 async function submit(e){e.preventDefault();setError("");setSuccess("");if(!form.role||!form.fullName.trim()||!form.email.trim())return setError("Role, full name and email are required.");if(form.password.length<6)return setError("Password must be at least 6 characters.");if(form.password!==form.confirmPassword)return setError("Passwords do not match.");setLoading(true);try{const payload={fullName:form.fullName,email:form.email,phone:form.phone,password:form.password,role:form.role};if(form.role==="TEACHER")Object.assign(payload,{employeeId:form.employeeId,qualification:form.qualification,experience:form.experience});const d=await apiRequest("/auth/register",{method:"POST",body:JSON.stringify(payload)});setSuccess(`Account created for ${d.user.fullName}. You can now log in.`);setForm(initial)}catch(e){setError(e.message)}finally{setLoading(false)}}
 return <div className="login register-page"><form className="register-card" onSubmit={submit}><div className="login__header"><span className="login__icon">🏫</span><h1 className="login__title">Bright Future School</h1><p className="login__subtitle">Create your account</p></div>{error&&<div className="form-message form-message--error">{error}</div>}{success&&<div className="form-message form-message--success">{success}</div>}<div className="login__field"><label className="login__label">Register As</label><div className="register-roles">{roles.map(r=><button type="button" key={r.value} disabled={!availability[r.value]} onClick={()=>update("role",r.value)} className={`register-role ${form.role===r.value?"register-role--active":""}`}>{r.label}<span>{availability[r.value]?r.description:"Limit reached"}</span></button>)}</div></div><div className="form-grid"><Field label="Full Name" value={form.fullName} onChange={v=>update("fullName",v)} required/><Field label="Phone" value={form.phone} onChange={v=>update("phone",v)}/><Field label="Email" type="email" value={form.email} onChange={v=>update("email",v)} required/><Field label="Password" type="password" value={form.password} onChange={v=>update("password",v)} required/><Field label="Confirm Password" type="password" value={form.confirmPassword} onChange={v=>update("confirmPassword",v)} required/></div>{form.role==="TEACHER"&&<div className="register-teacher"><div className="form-grid"><Field label="Employee ID" value={form.employeeId} onChange={v=>update("employeeId",v)}/><Field label="Experience" value={form.experience} onChange={v=>update("experience",v)}/><Field label="Qualification" value={form.qualification} onChange={v=>update("qualification",v)}/></div></div>}<button className="login__btn" disabled={loading}>{loading?"Creating account...":"Create Account →"}</button><p className="login__register">Already have an account? <Link to="/login">Log in</Link></p></form></div>}
function Field({label,value,onChange,type="text",required=false}){return <label className="form-group"><span className="form-label">{label}</span><input className="form-input" type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
