import { useEffect, useState } from "react";
import { apiRequest } from "../api";

export default function Subjects({ role, cfg }) {
  const [subjects,setSubjects]=useState([]),[classes,setClasses]=useState([]),[teachers,setTeachers]=useState([]),[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[error,setError]=useState("");
  const [form,setForm]=useState({name:"",code:"",class:"",section:"",teacher:""});
  const canEdit=role!=="teacher";
  async function load(){try{const calls=[apiRequest("/subjects"),apiRequest("/classes")];if(canEdit)calls.push(apiRequest("/teachers"));const data=await Promise.all(calls);setSubjects(data[0].subjects||[]);setClasses(data[1].classes||[]);if(canEdit)setTeachers(data[2].teachers||[]);}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[]);
  function edit(s){setEditing(s._id);setForm({name:s.name||"",code:s.code||"",class:s.class?._id||"",section:s.section||"",teacher:s.teacher?._id||""});setOpen(true)}
  async function save(e){e.preventDefault();setError("");try{if(editing)await apiRequest(`/subjects/${editing}`,{method:"PUT",body:JSON.stringify(form)});else await apiRequest("/subjects",{method:"POST",body:JSON.stringify(form)});setOpen(false);load()}catch(e){setError(e.message)}}
  async function remove(id){if(!confirm("Delete this subject?"))return;try{await apiRequest(`/subjects/${id}`,{method:"DELETE"});load()}catch(e){setError(e.message)}}
  return <div className="page"><div className="page__header"><div className="page__header-row"><div><h2 className="page__title">{role==="teacher"?"My Subjects":"Subjects"}</h2><p className="page__subtitle">Manage school subjects</p></div>{canEdit&&<button className="btn btn--primary" style={{backgroundColor:cfg.color}} onClick={()=>{setEditing(null);setForm({name:"",code:"",class:"",section:"",teacher:""});setOpen(true)}}>+ Add Subject</button>}</div></div>{error&&<div className="form-message form-message--error">{error}</div>}<div className="subject-cards">{subjects.map(s=><div className="subject-card" key={s._id} style={{borderTopColor:cfg.color}}><p className="subject-card__name">{s.name}</p><p className="subject-card__meta">Code: {s.code}</p><p className="subject-card__meta">Class: {s.class?.name||"—"}-{s.section}</p><p className="subject-card__meta">Teacher: {s.teacher?.fullName||"Unassigned"}</p>{canEdit&&<div className="card-actions"><button className="link-btn" style={{color:cfg.color}} onClick={()=>edit(s)}>Edit</button><button className="link-btn danger-link" onClick={()=>remove(s._id)}>Delete</button></div>}</div>)}</div>{open&&<div className="modal-backdrop"><form className="modal-card" onSubmit={save}><div className="modal-header"><h3>{editing?"Edit Subject":"Add Subject"}</h3><button type="button" className="modal-close" onClick={()=>setOpen(false)}>✕</button></div><div className="form-grid"><Field label="Subject Name" value={form.name} onChange={v=>setForm({...form,name:v})} required/><Field label="Code" value={form.code} onChange={v=>setForm({...form,code:v})} required/><Select label="Class" value={form.class} onChange={v=>setForm({...form,class:v})} options={classes.map(c=>[c._id,c.name])} required/><Field label="Section" value={form.section} onChange={v=>setForm({...form,section:v})} required/><Select label="Teacher" value={form.teacher} onChange={v=>setForm({...form,teacher:v})} options={teachers.map(t=>[t._id,t.fullName])}/></div><div className="modal-actions"><button type="button" className="btn" onClick={()=>setOpen(false)}>Cancel</button><button className="btn btn--primary" style={{backgroundColor:cfg.color}}>{editing?"Update Subject":"Save Subject"}</button></div></form></div>}</div>
}
function Field({label,value,onChange,required=false}){return <label className="form-group"><span className="form-label">{label}</span><input className="form-input" value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function Select({label,value,onChange,options,required=false}){return <label className="form-group"><span className="form-label">{label}</span><select className="form-select" value={value} onChange={e=>onChange(e.target.value)} required={required}><option value="">Select {label.toLowerCase()}</option>{options.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}
